### ISSUE TITLE
Request for Code Release

### ISSUE THREAD

**Issue by went-lee** [bmi-imaginelab/SI-MIL#1]
I am very interested in your research. May I ask when the code will be released? Thank you.

**Comment by saarthak-kapse** [comment]
Hi Went-lee, thank you for your interest in our research! I have cleaned up the MIL part of the code and uploaded it now. I am currently cleaning and organizing the feature extraction part of code and expect to upload that and update the readme file by May 15 at the most. 

I have also uploaded the handcrafted and deep features along with cell maps from HoVer-Net.
