### ISSUE TITLE
Data Spliting

### ISSUE THREAD

**Issue by jingweitan** [bmi-imaginelab/SI-MIL#2]
Thanks for your awesome work. 
Can I get the list of train, validation and test set list for the dataset spliting ?

Thanks in advance.

**Comment by saarthak-kapse** [comment]
Hi Jingwei, thank you for appreciating our work. 

The train/test split is available here: https://stonybrookmedicine.app.box.com/s/ewylzthdisg5j5fvqsi2etpedqvc409v. You can go through the train_dict.pickle and test_dict.pickle in each cancer's PathExpert features folder for list of WSI in train/test split. We don't have an explicit validation split and instead we randomly select 20% from the training split in each of the 5-fold cross-validation. 

Please feel free to reach out if you have any further doubts.
